### ISSUE TITLE
デザインコンセプトを決める

### ISSUE THREAD

**Issue by mataku** [pepabo-mobile-app-training/sunset#1]
アプリのコンセプトを決めよう！

**Comment by mataku** [comment]
### コンセプト図

メイン画面

![slack for ios upload-7](https://cloud.githubusercontent.com/assets/13099942/18244172/91e17c5c-7399-11e6-86ac-0daa9d70d017.jpg)

**Comment by Asuforce** [comment]
launch screen

![launch](https://cloud.githubusercontent.com/assets/9331040/18262728/2fcc4bd6-743f-11e6-8740-51b7209af652.png)

webview

![webview](https://cloud.githubusercontent.com/assets/9331040/18262754/6a1e5e6e-743f-11e6-8190-7ec15248b314.png)

**Comment by Asuforce** [comment]
### デザインコンセプトについて 9/6
- [hashicorp](https://www.hashicorp.com/) っぽい感じ
- 六角形を多用したい
- 夕暮れっぽい、暗すぎない感じ

**Comment by Asuforce** [comment]
### デザインコンセプトについて 10/11
- 全体で統一感を出したい
- 夕暮れっぽい感じは変わらず、sunsetがテーマ
- 六角形でなくてもよさそう、むしろ丸とかのほうがよい

#### アプリ内のデザイン
- 空 → 海
- 一日をどう表現するか、時の経過

#### イメージ

![2016-10-11 12 18 32](https://cloud.githubusercontent.com/assets/9331040/19259300/279549e4-8fbb-11e6-8571-d7c81bcdf14b.jpg)

**Comment by Asuforce** [comment]
### デザインコンセプトについて 10/12

デザイン以外の実装についても話し合いました
- グラデーション
  - コンテナビューごとに分けずに一枚に適用してみる
  - 数字の色も最適化したい
- カレンダー縦横
  - とりあえずカレンダーはスクロール無しの全表示にする
  - 実際にユーザーテストして、数字のタップのし易さなどを調査する
- realm
  - core dataより良さそう
  - 時間があれば
- 六角形はどうするか
  - [当初](https://github.com/pepabo-mobile-app-training/sunset/issues/1#issuecomment-244854529)は暗いアプリをイメージしていた
  - [コンセプト](https://github.com/pepabo-mobile-app-training/sunset/issues/4)が決まって、一日の終わりのまだ暗くない感じのイメージに変わった
  - 六角形はきっちりした感じだからイメージとズレる、そのため丸を基調とした図形を使っていく方針に
- カレンダーセルタップ時の動作
  - 上記の背景より数字を白塗りの円で囲むようにする
- 起動画面
  - 実写より絵の方がイメージに合いそう
  - 全面じゃなくて中心に絵を寄せる形にする
- アイコン左寄りに見える
  - ペンを無くすとよいか試してみる
