### ISSUE TITLE
開発方針について

### ISSUE THREAD

**Issue by mataku** [pepabo-mobile-app-training/sunset#10]
### 概要

開発方針について、ログを残します。

**Comment by mataku** [comment]
### 外部パッケージのビルドによってCIに時間がかかった

#### 原因

carthageによって導入されたパッケージのビルドを毎回しているので、遅かった

#### 対策

bitrise側でキャッシュを使うように設定した
- carthageのステップ前に`cache:pull`, ステップ後に`cache:push`で解決

**Comment by mataku** [comment]
### Xcodeのテストが何事もなく終了する
- ログ (UITestで落ちてる？) 

```
All tests
Test Suite sunsetTests.xctest started
sunsetTests
    ✓ testExample (0.001 seconds)
    ◷ testPerformanceExample measured (0.000 seconds)
    ✓ testPerformanceExample (0.403 seconds)


     Executed 2 tests, with 0 failures (0 unexpected) in 0.403 (0.405) seconds

isRetryOnFail=false, no more retry, stopping the test!
xcode test exit code: 65
xcode test failed, error: exit status 65
```

#### 原因
- UITestに何かを記述していたわけではないので、内容のエラーではない

#### 対策
- xcode testステップにて`clean build`を毎回するように指定したらエラーがなくなった

**Comment by Asuforce** [comment]
### コメントについて
- 以下のような自動生成されるコメントを消す

![2016-09-26 14 45 03](https://cloud.githubusercontent.com/assets/9331040/18823761/db7b875e-83f7-11e6-9852-be8439e7d551.png)

**Comment by Asuforce** [comment]
### Storyboardの運用について
- 画面ごとにStoryboardを作る
- [Storyboard名]ViewControllerを作成する
  - 生成されたView ControllerのCustom Classを設定する
- レビューの際は画像を添付する

**Comment by mataku** [comment]
## 開発・及びレビュー工程について
- テストをできるだけ書く
  - UITestで確認できないところは実機テストをレビュワーにしてもらうことで担保する
- https://github.com/pepabo-mobile-app-training/sunset/issues/37 のテンプレートを元に、レビュー依頼を出す

**Comment by mataku** [comment]
## アプリのスリープ設定について
- デフォルトではスリープする設定になっている
  - ビルドして入れた一発目は、stopを押すまで表示されるようになっているので分かりづらい

### 変更方法
- AppDelegate.swiftへ追記する

``` swift
func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
    UIApplication.shared.isIdleTimerDisabled = true
    return true
}
```

**Comment by mataku** [comment]
## Twitter連携への道
- [ ] Twitter認証関連のライブラリの導入
- [ ] ログイン画面の実装
- [ ] TwitterのApiClient、Tweetモデル (Realm) を作成
- [ ] 保存する対象をTweetにする
- [ ] 優勝

**Comment by mataku** [comment]
## Cocoapods導入に伴う色々なこと

### 開くべきプロジェクトファイルが変わった
- project.pbxprojからsunset.xcworkspaceに変わりました

### Bitrise CIの設定
- 上の設定変更をWorkflowの`App Env vars`よりしないと永遠にちゃんとしたビルドが走らないので注意

### 管理
- cocoapodsはRuby Gem
- PodfileとPodfile.lock
  - pod installするとこれらをもとにインストールされる
  - bundlerかよ

**Comment by mataku** [comment]
## Fabric導入について

### インストール -> pod install
- Podfile
- `target`を書かないといけなくなったらしい

``` ruby
target 'sunset' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  pod 'TwitterKit'

  # Pods for sunset

  target 'sunsetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sunsetUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### 色んなキーについて
- FABRIC_API_KEY, FABRIC_BUILD_SECRET
  - fabricより取得
  - https://fabric.io/kits/ios/twitterkit/install
- Twitter consumer_key, consumer_secret
  - Twitterより取得
  - https://dev.twitter.com

### 鍵の管理
- Fabricは認証されてないと使えないので、鍵をプロジェクト内に読み込ませる必要がある
- Run scriptや、コード内に直書きしていると危険

#### コード内で鍵を読み込ませたいときは？

`cocoapods-keys`を使おう！
- `.env`内の環境変数を読み込ませることができる
- [cocoapods-keysをSwiftのプロジェクトで利用する](http://qiita.com/satoshin2071/items/880ebdfe84dc6a6c8fbf)
- PodfileへKeyの名前を追記して、pod install

```
plugin 'cocoapods-keys', {
  :project => 'sunset',
  :keys => [
    'APIKEY',
    'BUILDSECRET',
    'consumerKey',
    'consumerSecret'
  ]
}
```
- keysは.envのkey (.envにおける、key=valueの式の左辺)と合わせる

#### Run Scriptで使いたい
- `.env`を読み込んで、環境変数としておけば`$YEAH`とかで参照できる
- オープンなリポジトリだったらリモートにはあげられないので、あったら読み込ませるようにした方が良い

``` bash
if [ -e .env ]; then
  source .env
fi
```
- CI上ではあらかじめWorkflowの`secret key vars`に定義しておくと良い
