### ISSUE TITLE
ハマリポイント・メモなど

### ISSUE THREAD

**Issue by mataku** [pepabo-mobile-app-training/sunset#14]
## 概要

はまった所ログ

**Comment by mataku** [comment]
## storyboardからラベルなどをドラッグできなくなった

### 症状

storyboardからラベルやボタン等をドラッグしてもエラーになった

```
Could not insert new outlet connection: Could not find any information for the class and not showing any class named CalendarViewController
```

### 対処

参考ページ: Xcodeのストーリーボードでボタンをドラッグアンドドロップ出来ない問題
http://qiita.com/nagahori/items/71c1940319d35fa886f5

(xcodeのキャッシュが悪さをしていたっぽいので以下のコマンドで消した)

``` bash
rm -rf ~/Library/Caches/com.apple.dt.Xcode
defaults delete com.apple.dt.Xcode IDEIndexDisable  
defaults write com.apple.dt.Xcode IDEIndexEnable 1
```

**Comment by Asuforce** [comment]
## ViewControllerの関連付け

### 症状

ViewControllerを作成した際にstoryboardに関連付けできなくなった
いつも通り以下の方法で実践しても動かなかった
[【swift】複数のViewControllerを使う](http://swiftfe0.hatenablog.com/entry/2016/07/22/235638)

### 対処

storyboardでtable view controllerを使っていたのが原因だった
作成したViewControllerでUITableViewControllerを継承すれば直った

**Comment by mataku** [comment]
## Bitrise上でのschemeに関するwarningについて

### 問題

Xcodeのプロジェクトのビルド Scheme は、デフォルトではプロジェクトファイルに紐付いておらず
バージョン管理ツールにコミットしても他のユーザに共有できなかった

### 対策

`Project -> Scheme -> Manage Schemes...`を選択し、対象のschemeにチェックを入れるとwarningが解消された

### 参考ページ

https://github.com/pepabo-mobile-app-training/turmeric/pull/11

**Comment by mataku** [comment]
## ローカルではテストが通るけど、Bitrise CIで通らない

### 症状
- ローカルでは何事もなく通るけれど、Bitriseでは通らない

### 対策
- まずログ (raw-xcodebuild-output.log) を見る
  - bitriseページの`Build log`の上にある
  - ひとまずローカルでのブランチ (及び内容)が一致していることを確認
- `clean build`のチェック
  - bitriseの設定より確認
- 非同期処理を疑う
  - [おぎのコメント (API clientを作っていた時に起こったもの)](https://github.com/pepabo-mobile-app-training/turmeric/pull/12/files/5981e77f546690f5ca28b3978b0c2f8f6036cf75#r80833162)
  - 処理終わる前にテストが終了してエラーになるらしい

**Comment by Asuforce** [comment]
## 単体testで外部ライブラリが使えない

### 対策
- プロジェクトファイルの設定からターゲットをTestsに切り替えて`Link Binary With Libraries`にライブラリを追加する

**Comment by Asuforce** [comment]
## APIのテストがCI上で通らない

### 症状
- apiのテストがCIで通らない、通信がうまくできてない？

### 対策
- stubを使ってapiのモックを作る
  - OHHTTPStubsを併せて使うと作りやすい

**Comment by Asuforce** [comment]
## UIテストでstubが使いたい

### 症状
- 単体テストのようにsetUpメソッドに定義してもstubが使えない...

### 対策
- AppDelegateにstubの処理を記述し、UIテストのアプリ起動時に環境変数から呼び出す([詳細](http://stackoverflow.com/questions/32827592/is-it-possible-to-stub-http-requests-in-xcode-7-automated-ui-tests))

**Comment by mataku** [comment]
## Storyboard上に複数のviewを置きたい

### やりたいこと
- 1つのStoryboardに複数のviewを表示 (ここではcollectionViewとtableView)
- 単一のViewVontrollerに、複数のViewに関するコードを詰め込むのはコードの管理上よろしくないと考えた
  - なのでControllerを分割する方向で、なおかつ1つのStoryboard上に複数Viewを表示させたかった

### 対策 (色々ありそう)
- `Container view`を使おう
  - Container viewを置くとそこの領域を別のviewControllerに持たせることが出来るゾ
- (以下、やったことまとめ)

```
1. Container Viewを表示させたいStoryboard上に置く
2. デフォルトではUIViewが用意されてContainer viewにsegueで繋がれるので、
   他のものを使いたい場合は別のものを用意して、segueをつなぎ直す
3. つなぎ直した場合は、アクション(?)をembedにすると、そこに埋め込まれるようになるので、分割したいViewをそこに書いていく
4. 優勝
```

**Comment by mataku** [comment]
## 全体の表示

### 1 (calendar) : 1 (micropost)

## カレンダーの表示比

### 1 (header) : 5 (calendar)

<img width="355" alt="2016-09-29 12 22 28" src="https://cloud.githubusercontent.com/assets/13099942/18939961/6f327572-863f-11e6-8522-47971d42786b.png">

**Comment by mataku** [comment]
### データを永続化を考える際に良さそうなページ

【SWIFT 2.0】CORE DATA 入門、チュートリアル【図解】
http://www.anvariation.com/coredata-tutorial/

**Comment by Asuforce** [comment]
### Viewのマージン設定について

http://qiita.com/yimajo/items/10f16629200f1beb7852
http://blogios.stack3.net/archives/2334

### ATSについて

http://hitoriblog.com/?p=41624
[Apple 公式](https://developer.apple.com/library/prerelease/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW44)

### WebViewのUIテストについて

http://stackoverflow.com/questions/32623869/testing-uiwebview-with-xcode-ui-testing

### Swiftの基礎

http://swift-ios.keicode.com/

**Comment by Asuforce** [comment]
### 画面遷移時に値を渡す

http://qiita.com/senseiswift/items/20d09c523772caaf8005
http://qiita.com/moai_S2/items/e1cce9f3ff67fb897da5

**Comment by Asuforce** [comment]
### アイコンの設定

http://swift-bettychang.hatenadiary.jp/entry/2016/01/05/185303

**Comment by Asuforce** [comment]
### UITableViewがずれる

http://qiita.com/tomosooon/items/2c9725896803f090698d

**Comment by mataku** [comment]
### 変数の型を知りたい (デバッグ用)

`type(of: 変数名)`

**Comment by Asuforce** [comment]
### iOSアプリでやってしまいがちなバグと対策

http://qiita.com/musclemikiya/items/5528c2d2418ebeade7b4

**Comment by mataku** [comment]
## 実機にインストールできない時の対策
1. XCode -> Preferences -> Accounts -> 該当のApple IDをクリック -> View Details... を見る
2. 該当のProfilesをダウンロードして`Done`
3. buildする前にclean (command + shift + k) を行い、再度ビルド

## それでも通らない場合は...
- XCodeのプロジェクト設定を見よう
  - プロジェクトのターゲットでアプリを選択し、Generalタブを選択
  - `Automatically manage signing`をし直す

<img width="658" alt="2016-10-07 16 23 07" src="https://cloud.githubusercontent.com/assets/13099942/19181800/6156cb58-8caa-11e6-8f50-964a1bec7fc9.png">

**Comment by Asuforce** [comment]
### navigationbarを透過させたい

http://stackoverflow.com/questions/2315862/make-uinavigationbar-transparent

**Comment by mataku** [comment]
## 簡単なアプリアイコンの作り方 (イラレ不要)

http://qiita.com/seihmd/items/25f2a42e20e88ea5d86f
