### ISSUE TITLE
開発情報まとめ

### ISSUE THREAD

**Issue by Asuforce** [pepabo-mobile-app-training/sunset#3]
開発に関する情報をまとめます

**Comment by Asuforce** [comment]
カレンダー
http://qiita.com/sakuran/items/3c2c9f22cbcbf4aff731

cellの大きさ変更
http://qiita.com/MilanistaDev/items/fbf5fb890d9a3a7180cd

プラグイン一覧
http://qiita.com/tattn/items/238b2b813be16f830bd4

ビルド時間の短縮
http://techblog.timers-inc.com/entry/2016/07/06/183632

**Comment by mataku** [comment]
ビュー自体の大きさを端末に合わせた比で表示
http://qiita.com/tmokita/items/abf8ec17469185de2d97

**Comment by Asuforce** [comment]
Food tracker
http://qiita.com/taji-taji/items/9202d944bf403957a22e
