### ISSUE TITLE
サービスコンセプトについて

### ISSUE THREAD

**Issue by mataku** [pepabo-mobile-app-training/sunset#4]
### 概要

サービスコンセプトについて考えます

デザインコンセプトはこちら -> https://github.com/pepabo-mobile-app-training/sunset/issues/1

**Comment by Asuforce** [comment]
### 9/6 初期のコンセプト

![](http://i.imgur.com/zGl1zmH.jpg)

**Comment by Asuforce** [comment]
### 9/23 改めて考え直した

![](http://i.imgur.com/WxL08AX.jpg)

**Comment by Asuforce** [comment]
### ポエム

友達と買い物をしている私　は本当の私
アイドルの推しについて熱狂的につぶやいている私　も本当の私
本当の私　はここにある

**Comment by Asuforce** [comment]
### コンセプト

私の人生がここにある
