### ISSUE TITLE
起動画面について

### ISSUE THREAD

**Issue by mataku** [pepabo-mobile-app-training/sunset#48]
## 概要

起動画面案を貼っつけていきます
デザインコンセプト -> #1 
## 今のやつ

![sunset-back](https://cloud.githubusercontent.com/assets/13099942/19339468/7d0d8aae-915e-11e6-98d5-013a15fd89cd.jpg)

**Comment by mataku** [comment]
![1](https://cloud.githubusercontent.com/assets/13099942/19339375/023afafa-915e-11e6-938f-1798fa4370fe.png)

**Comment by Asuforce** [comment]
もっと濃いオレンジでもいいかもしれないですね

**Comment by mataku** [comment]
### 濃くした

![1](https://cloud.githubusercontent.com/assets/13099942/19341698/7f8799ae-9169-11e6-8c22-09c6e8984d7e.png)
